b2c2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    path("api/", include("order_engine.urls")),
    path("", include("trade_account.urls")),
    path("accounts/", include("allauth.urls")),
]

order_engine/urls.py
from django.conf.urls import url

from order_engine.handlers.balance_handler import BalanceHandler
from order_engine.handlers.open_positions_handler import OpenPositionsHandler
from order_engine.handlers.rfq_handler import RfqHandler
from order_engine.handlers.order_handler import OrderHandler

app_name = 'order_engine'

urlpatterns = [
    url(r'^balance$', BalanceHandler.as_view(), name='get_balance'),
    url(r'^rfq$', RfqHandler.as_view(), name='rfq_handler'),
    url(r'^order$', OrderHandler.as_view(), name='order_handler'),
    url(r'^open_positions$', OpenPositionsHandler.as_view(), name='open_positions'),
]

trade_account/urls.py
from django.conf.urls import url
from trade_account.views import DashboardHandler

app_name = 'trade_account'

urlpatterns = [
    url(r'^dashboard$', DashboardHandler.as_view(), name='dashboard'),
]

trade_account/models.py
from allauth.account.signals import user_signed_up
from annoying.fields import AutoOneToOneField
from django.db import models

from django.conf import settings
from django.dispatch import receiver

from utils.logging_util import log


class Profile(models.Model):
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    balances = models.JSONField(null=True, blank=True)
    b2c2_auth_token = models.CharField(max_length=64,
                                       # This is only here for the test
                                       default=settings.API_ENVIRONMENTS["B2C2"].get('authorization', ''))


@receiver(user_signed_up)
def user_signed_up_signal(request, user, **kwargs):
    Profile.objects.create(user=user)
    log.info("Profile created")

trade_account/forms.py
from django import forms
from django_utils.choices import Choice

from apis.b2c2_api.b2c2_constants import B2C2BuySellSide


class RfqForm(forms.Form):
    instruments = forms.CharField(max_length=64,
                                  widget=forms.Select(choices=[], attrs={'required': 'True'}),
                                  required=True,
                                  min_length=3)
    buy_sell = forms.CharField(widget=forms.Select(choices=[(side, side) for side in B2C2BuySellSide.options()],
                                                   attrs={'required': 'True'}),
                               max_length=64,
                               label="Side",
                               required=True,
                               min_length=3)
    quantity = forms.DecimalField(max_digits=6,
                                  widget=forms.NumberInput(attrs={"required": "required", "step": "0.0001"}),
                                  help_text="Max up to 6 digits", required=True, )
    session = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        instruments_choices = kwargs.pop("instruments_choices", None)
        super().__init__(*args, **kwargs)
        if instruments_choices:
            choices = [(inst_name, Choice(inst_name, inst_name)) for inst_name in instruments_choices]
            self.fields["instruments"].choices = choices
            self.fields["instruments"].widget.choices = choices

trade_account/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from rest_framework.views import APIView
from django.contrib.auth.mixins import LoginRequiredMixin
from apis.b2c2_api.b2c2_services import B2C2InstrumentsService
from order_engine.views import get_processed_balance_service
from trade_account.forms import RfqForm


class DashboardHandler(LoginRequiredMixin, APIView):
    login_url = reverse_lazy("account_login")

    def get(self, request):
        profile = request.user.profile
        instruments_service = B2C2InstrumentsService(profile.b2c2_auth_token)
        instruments_service.process_response(instruments_service.get_instruments())
        initial_data = {"session": self.request.session.session_key}
        if instruments_service.is_valid:
            form = RfqForm(initial=initial_data,
                           instruments_choices=instruments_service.output.all_instruments)
            template_context = {"form": form}
            _ = get_processed_balance_service(profile.b2c2_auth_token, template_context)
            return render(request, "dashboard.html", template_context)
        else:
            messages.error(request, instruments_service.rest_backend.exception_message, extra_tags="danger")
            return render(request, "dashboard.html", {"form": RfqForm(initial=initial_data), "balance_data": {}})

trade_account/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content_outside_container %}
    <section class="container pt-3">
        <h1 class="text-md-left text-center pt-4">Dashboard</h1>
        <h2 class="text-center" id="digital-time-div"></h2>
        <br>
        <div class="row">
            <div class="col-12" id="alert-danger-col" style="display: none">
                <div class="alert alert-danger" role="alert">
                    <div id="alert-danger-text"></div>
                </div>
            </div>
            <div class="col-12" id="alert-success-col" style="display: none">
                <div class="alert alert-success" role="alert">
                    <div id="alert-success-text"></div>
                </div>
            </div>
            <div class="col-12" id="modal-col" style="display: none">
                <div class="modal fade" id="rfq-modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">RFQ Confirmation</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body" id="rfq-modal-body">
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="rfq-modal-accept-btn" class="btn btn-success">Accept</button>
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Decline</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <h2 class="pb-3">Balances</h2>
                <div class="row" id="balance-data-row">
                    {% if balance_data %}
                        {% for currency, balance in balance_data.items %}
                            <div class="col-6 col-md-3">
                                <p>{{ balance }} <span style="font-weight: bold">{{ currency }}</span></p>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>Looks like we couldn't fetch any balance data, try again later.</p>
                    {% endif %}
                </div>
                <hr>
                <div class="col-12">
                    <h2 class="pb-3">RFQ</h2>
                    <form id="rfq-form" action="{% url "order_engine:rfq_handler" %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <br>
                        <button id="rfq-form-btn" class="btn btn-primary" type="submit">RFQ</button>
                        <button id="get-open-positions-btn" class="btn btn-warning">Get Open Positions</button>
                    </form>
                </div>
                <br>
            </div>
    </section>
{% endblock %}